spring:
  application:
    name: digital-wallet-challenge
  profiles:
    active: dev

server:
  port: 8084

jwt:
  secret: 59b99a3fd4233fcee4f9d2defa0ab23f2df6f065f9faf7d4514291e01288bb61
  expiration: 3600000